name: insnav
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aioice==0.10.2
      - aiortc==1.14.0
      - aiosignal==1.4.0
      - alembic==1.17.2
      - altair==6.0.0
      - amqp==5.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - argcomplete==3.6.3
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.1.0
      - blinker==1.9.0
      - catkin-pkg==1.1.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colcon-argcomplete==0.3.3
      - colcon-bash==0.5.0
      - colcon-cd==0.1.1
      - colcon-cmake==0.2.29
      - colcon-common-extensions==0.3.0
      - colcon-core==0.20.1
      - colcon-defaults==0.2.9
      - colcon-devtools==0.3.0
      - colcon-library-path==0.2.1
      - colcon-metadata==0.2.5
      - colcon-notification==0.3.0
      - colcon-output==0.2.13
      - colcon-package-information==0.4.0
      - colcon-package-selection==0.2.10
      - colcon-parallel-executor==0.4.0
      - colcon-pkg-config==0.1.0
      - colcon-powershell==0.4.0
      - colcon-python-setup-py==0.2.9
      - colcon-recursive-crawl==0.2.3
      - colcon-ros==0.5.0
      - colcon-test-result==0.3.8
      - colcon-zsh==0.5.0
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - coverage==7.13.1
      - cryptography==46.0.3
      - cycler==0.12.1
      - dash==3.3.0
      - decorator==5.2.1
      - distlib==0.4.0
      - distro==1.9.0
      - dnspython==2.8.0
      - docutils==0.22.4
      - einops==0.8.1
      - empy==4.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.3
      - flask==3.1.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - fvcore==0.1.5.post20221221
      - google-crc32c==1.8.0
      - greenlet==3.3.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - ifaddr==0.2.0
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - iopath==0.1.10
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.15.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notify2==0.3.1
      - numpy==2.2.6
      - numpy-quaternion==2024.0.13
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - open3d==0.18.0
      - openai==1.45.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathfinding==1.0.19
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - plotly==6.5.1
      - pluggy==1.6.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.11
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyee==13.0.0
      - pygments==2.19.2
      - pylibsrtp==1.0.0
      - pyopenssl==25.3.0
      - pyparsing==3.3.1
      - pyquaternion==0.9.9
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - pytest-repeat==0.9.4
      - pytest-rerunfailures==16.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.3
      - retrying==1.4.2
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools==79.0.1
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - timm==1.0.24
      - tokenizers==0.13.3
      - tomli==2.4.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.26.1
      - triton==3.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - vine==5.1.0
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - yacs==0.1.8
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/yin/miniconda3/envs/insnav
